### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by BigBen2003** [jnweiger/inkscape-input-stl#6]
Inkscape version 1.2 runs on Windows 10.

The files input-stl.py and input-stl.inx have been saved in the path C:\program files\inkscape\share\inkscape\extensions.

When importing an STL file the following error is displayed:

Traceback (most recent call last):
  File "C:\Program Files\Inkscape\lib\python3.9\sre_parse.py", line 1041, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\U'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Inkscape\share\inkscape\extensions\input-stl.py", line 58, in <module>
    args.slic3r_cmd = re.sub('^\$HOME(PATH)?', home, args.slic3r_cmd)
  File "C:\Program Files\Inkscape\lib\python3.9\re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Program Files\Inkscape\lib\python3.9\re.py", line 327, in _subx
    template = _compile_repl(template, pattern)
  File "C:\Program Files\Inkscape\lib\python3.9\re.py", line 318, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:\Program Files\Inkscape\lib\python3.9\sre_parse.py", line 1044, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \U at position 0

**Comment by BigBen2003** [comment]
You don't need this plugin to convert an STL file to an SVG.

The Slic3r already has such a function built in:
![image](https://github.com/jnweiger/inkscape-input-stl/assets/42717652/41a1a0f9-8be3-472c-b6f1-752ea95c69e4)
The command "File -> Slice to SVG" can be used to call up a wizard that converts any STL file into an SVG file.
